import Head from "next/head";
import { Header } from "../Header";
import { Footer } from "../Footer";

export const Whiskey = ({
  pageContent,
  mainMenuItems,
  callToAction,
  mainLogo,
}) => {
  return (
    <>
      <Head>
        <title>Dram Adventure - {pageContent.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        items={mainMenuItems}
        callToAction={callToAction}
        mainLogo={mainLogo}
      />
      <main>
        <h1>{pageContent.title}</h1>
      </main>
      <Footer />
    </>
  );
};
